language: node_js
cache:
  yarn: true
  directories:
  - node_modules
script:
  - NODE_ENV=test npm test
after_success:
 - NODE_ENV=production npm run build:web
before_deploy:
- rm -rf node_modules
deploy:
  - provider: heroku
    api_key:
      secure: B4rm1T3rzlSTuSK1QIKjwEdh58twL5gUYhrX73mtB4z1YlFbh3ZVlzV1bK+IRN8/znTHOErp9ZFb88PoGSKLbjN3o19Sumg6GdkFvMdbNXb2sQHm4zxTuyUJP1Px5gZMCXkAbs2UyBFI64oSfX3m3O+kS6B7dCqDzkzJ/YB53bQ99QwF2pIudAe8QnraMt5BNyx7HZwld6anJoCmzPxrO3pFuCwukJ+wPiC/qaWztBVZF0xubXkTpsQv8GuL94S+dWR6ZMYOCBtxunHadTknu1JHDBQ9zg3LfspdpmCmVoTl6PGQ1GchD5WL2ebplK42R+lm0lghd6+jEyBUngqCuB8Pj6hoQogPPDG7Oy4Z5Lpt4ZYjMBSB0O8p+KTgBIbm8Z8bo353XkymwA1mtPJeWFDjVqm3qUTQtqtO4OgslrGSW6g1+tuqs0+ONySHojTtmoRgaSTqGT+QcPbVY4facwop7TiyEWb9qJiD0amtnUVUFIHiTx/Anv1wK7ivWe1xwZqJpFaZg/PUzO1BzhWK2pqBX+9Nyd3xNFC4WlshSBeMLr/VvlpRR3fuWjJmRbpxGjZ8L2FW0kWkmRkcaOg4XKAn5LpPLaNhxB7BOTEzWC2aHdspJMkloaQb42G5osanh4nwmc4B6/CWPoPYtXKPy+BVsbu99dv51scm63BrWTY=
    app: coinaly
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: B4rm1T3rzlSTuSK1QIKjwEdh58twL5gUYhrX73mtB4z1YlFbh3ZVlzV1bK+IRN8/znTHOErp9ZFb88PoGSKLbjN3o19Sumg6GdkFvMdbNXb2sQHm4zxTuyUJP1Px5gZMCXkAbs2UyBFI64oSfX3m3O+kS6B7dCqDzkzJ/YB53bQ99QwF2pIudAe8QnraMt5BNyx7HZwld6anJoCmzPxrO3pFuCwukJ+wPiC/qaWztBVZF0xubXkTpsQv8GuL94S+dWR6ZMYOCBtxunHadTknu1JHDBQ9zg3LfspdpmCmVoTl6PGQ1GchD5WL2ebplK42R+lm0lghd6+jEyBUngqCuB8Pj6hoQogPPDG7Oy4Z5Lpt4ZYjMBSB0O8p+KTgBIbm8Z8bo353XkymwA1mtPJeWFDjVqm3qUTQtqtO4OgslrGSW6g1+tuqs0+ONySHojTtmoRgaSTqGT+QcPbVY4facwop7TiyEWb9qJiD0amtnUVUFIHiTx/Anv1wK7ivWe1xwZqJpFaZg/PUzO1BzhWK2pqBX+9Nyd3xNFC4WlshSBeMLr/VvlpRR3fuWjJmRbpxGjZ8L2FW0kWkmRkcaOg4XKAn5LpPLaNhxB7BOTEzWC2aHdspJMkloaQb42G5osanh4nwmc4B6/CWPoPYtXKPy+BVsbu99dv51scm63BrWTY=
    app: coinaly-api
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: B4rm1T3rzlSTuSK1QIKjwEdh58twL5gUYhrX73mtB4z1YlFbh3ZVlzV1bK+IRN8/znTHOErp9ZFb88PoGSKLbjN3o19Sumg6GdkFvMdbNXb2sQHm4zxTuyUJP1Px5gZMCXkAbs2UyBFI64oSfX3m3O+kS6B7dCqDzkzJ/YB53bQ99QwF2pIudAe8QnraMt5BNyx7HZwld6anJoCmzPxrO3pFuCwukJ+wPiC/qaWztBVZF0xubXkTpsQv8GuL94S+dWR6ZMYOCBtxunHadTknu1JHDBQ9zg3LfspdpmCmVoTl6PGQ1GchD5WL2ebplK42R+lm0lghd6+jEyBUngqCuB8Pj6hoQogPPDG7Oy4Z5Lpt4ZYjMBSB0O8p+KTgBIbm8Z8bo353XkymwA1mtPJeWFDjVqm3qUTQtqtO4OgslrGSW6g1+tuqs0+ONySHojTtmoRgaSTqGT+QcPbVY4facwop7TiyEWb9qJiD0amtnUVUFIHiTx/Anv1wK7ivWe1xwZqJpFaZg/PUzO1BzhWK2pqBX+9Nyd3xNFC4WlshSBeMLr/VvlpRR3fuWjJmRbpxGjZ8L2FW0kWkmRkcaOg4XKAn5LpPLaNhxB7BOTEzWC2aHdspJMkloaQb42G5osanh4nwmc4B6/CWPoPYtXKPy+BVsbu99dv51scm63BrWTY=
    app: coinaly-socket
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
