language: node_js
cache:
  yarn: true
  directories:
  - node_modules
script:
  - NODE_ENV=test npm test
after_success:
 - NODE_ENV=production npm run build:web
before_deploy:
- rm -r node_modules
deploy:
  - provider: heroku
    api_key:
      secure: EOoJ/O7cjdA5TfpYdnRWv2kE3n/qec+nX121j+ZKtIxlx5+06i8AC69qpSeUDZ29oJS4zdqzOWAuuY4S3pZjrP+FIw8CPrgNVu5anlM9A6uUjFLQG8m5PFZRG1WChUlzd+ghTZY6WyKzWiCz+2Hyhm/gQIQngloHktEvpsejcnqShbejdZQ0/mV8sDlXLY67d3L3Qw7tIZs/qKGPvaRHpdEr8i7gwhXEN4y66M8xC8M3R5mCtCW6kuFg7jtHXA8sBklcSVPVLauMQIvKAl/ic9JN8kCArlxt4n5IBXMF2h8285fht9mkwxn/cc/LIHKnSSPzW7GMG2cDNkR9t3FoXpdNd5DsYIkOxwqpr/x7lKJCJm9LSD+Tg5D7Lkj25oghpuXsdGDXzz2YV0joUJWsNjSlESvdb7NOVb266asPnMamq6bVr0xeZ53tByG9FSjr4VQ5jwTdeqwZCA+L+kGqn+fddImt5yBWzWl0Dk/HWxmQQKe843yiviaOfPAkb/IdPtgpmYTcVRczK4z8vDFHvZQuuVxpjRJ4HK07sjHKVsu49BKlgijhRSt/ktr4AfpO32xcmlILJhvgHYe4ovucFaG5gAzc19h1Ik261AvSPr7BHnMO/Bv3AT5qDfjuuTIjrlZ9pNihnAnHaFv/lqpBY84zS6w3rc00SlwdPwvNTKQ=
    app: coinaly
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: EOoJ/O7cjdA5TfpYdnRWv2kE3n/qec+nX121j+ZKtIxlx5+06i8AC69qpSeUDZ29oJS4zdqzOWAuuY4S3pZjrP+FIw8CPrgNVu5anlM9A6uUjFLQG8m5PFZRG1WChUlzd+ghTZY6WyKzWiCz+2Hyhm/gQIQngloHktEvpsejcnqShbejdZQ0/mV8sDlXLY67d3L3Qw7tIZs/qKGPvaRHpdEr8i7gwhXEN4y66M8xC8M3R5mCtCW6kuFg7jtHXA8sBklcSVPVLauMQIvKAl/ic9JN8kCArlxt4n5IBXMF2h8285fht9mkwxn/cc/LIHKnSSPzW7GMG2cDNkR9t3FoXpdNd5DsYIkOxwqpr/x7lKJCJm9LSD+Tg5D7Lkj25oghpuXsdGDXzz2YV0joUJWsNjSlESvdb7NOVb266asPnMamq6bVr0xeZ53tByG9FSjr4VQ5jwTdeqwZCA+L+kGqn+fddImt5yBWzWl0Dk/HWxmQQKe843yiviaOfPAkb/IdPtgpmYTcVRczK4z8vDFHvZQuuVxpjRJ4HK07sjHKVsu49BKlgijhRSt/ktr4AfpO32xcmlILJhvgHYe4ovucFaG5gAzc19h1Ik261AvSPr7BHnMO/Bv3AT5qDfjuuTIjrlZ9pNihnAnHaFv/lqpBY84zS6w3rc00SlwdPwvNTKQ=
    app: coinaly-api
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: EOoJ/O7cjdA5TfpYdnRWv2kE3n/qec+nX121j+ZKtIxlx5+06i8AC69qpSeUDZ29oJS4zdqzOWAuuY4S3pZjrP+FIw8CPrgNVu5anlM9A6uUjFLQG8m5PFZRG1WChUlzd+ghTZY6WyKzWiCz+2Hyhm/gQIQngloHktEvpsejcnqShbejdZQ0/mV8sDlXLY67d3L3Qw7tIZs/qKGPvaRHpdEr8i7gwhXEN4y66M8xC8M3R5mCtCW6kuFg7jtHXA8sBklcSVPVLauMQIvKAl/ic9JN8kCArlxt4n5IBXMF2h8285fht9mkwxn/cc/LIHKnSSPzW7GMG2cDNkR9t3FoXpdNd5DsYIkOxwqpr/x7lKJCJm9LSD+Tg5D7Lkj25oghpuXsdGDXzz2YV0joUJWsNjSlESvdb7NOVb266asPnMamq6bVr0xeZ53tByG9FSjr4VQ5jwTdeqwZCA+L+kGqn+fddImt5yBWzWl0Dk/HWxmQQKe843yiviaOfPAkb/IdPtgpmYTcVRczK4z8vDFHvZQuuVxpjRJ4HK07sjHKVsu49BKlgijhRSt/ktr4AfpO32xcmlILJhvgHYe4ovucFaG5gAzc19h1Ik261AvSPr7BHnMO/Bv3AT5qDfjuuTIjrlZ9pNihnAnHaFv/lqpBY84zS6w3rc00SlwdPwvNTKQ=
    app: coinaly-socket
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
