language: node_js
cache:
  yarn: true
  directories:
  - node_modules
script:
  - NODE_ENV=test npm test
after_success:
 - NODE_ENV=production npm run build:web
before_deploy:
- rm -rf node_modules
deploy:
  - provider: heroku
    api_key:
      secure: YcrCdtW52HAcNE2C4RKWkIIml5NN35V0S/1bvhjgxYDR8jrzueVYVSGHFuuZq2zZcQEjaK+Uv4KjAThsiFIvupOQKqZ2PG67ozIKkfbD/S8Zv6FOxvR35cmr1BHZNC3BriV2JkxlWnwl+49sSDIMfZ7A4CUKdvPKZBlkTXiZGhGi+uFu0/MfbhSTjSLje7HPvqpMjODWkQdygyKcGHczkruFHYJE0DNnCWjWRZ+T+BKhWYuRAVbiTR8vmETf9XNjyxIxbU+aeIPtQuKxQOGQMEodafwlgUA0C/92o7j52t8aa16yCIPl5Q+JuVsrW41mE/VgJbwyIcsbYD4HBIH6XOIDxLKMzx5+dODe6QWr8cLVpL7oMLedGBY8KOUubLvgaLVZUyLzehYeIE6pUUktCUBShhuzciWEkXtyvj3yXEy6QSZ3xy7BhsR8tc6IgdKv6QZedYNgNJmvCA0/lMRjycQBbjZpld6clJE9sfn+JFzkbZFSuwJRGxJcuVHwdD135zI4UxEiPPZcc/HfTzNSdNF7YlcY9J4TgA0uThY808rW6lozkjtbEksRF7nuevdUiuA7zEPjQP2jilg3pgHG8ya/Rqwm0sudtcTY5SBgczkdl6Kd0uQc0kyY8JjPitJE4PhJ1lDQsVNW3NFfvkwINtcKRv/+n8p90+Roh6xq9i8=
    app: coinaly-app
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: Vq3MB1GXJGI6CS2RzuQoMzwsvsl1q0GdpfXxDFCckxQXFLxToI2KyqsG97n9o0P1BW0wDtJtjgM9L5o1QW9PSnpWHCTMfqOiNPPUNW0gKb3KDHzLXAs885scD0bbSXZhC+XAGE1zTobu+rRz3CUyP1o7FHYduSIQRVfoVsl3Wo3ssLkrGijlOKcykDbInZrNjxslM96anBglqgiN4yL7aMAkY9ckPxGcAS615oOTeKmJpsb4q00l/38P5CWJJTYA/xOSWQ627htOsU1EHWAVkIXVcqe8aarIdtbjKqUeJ31FS3OuN5eEcRIRrkcuQ2SzZeNW3YiQomh/Dh0w1adWdSpqw+4wtRWX2wC53oBORWJwbpG0nJNJitTsbjPOQMeGOgNFvlz8A73O6jRaf45MkV4G97oDHK+EnOmTs3+FxSQRslLXNXBSUPkuuuSyLTcYY3hsFs1WQFtrW3JXjcxBiXKWdki4auk5mIKgoDsbfgOlGS6fzK800O0JZCedNCTP/5G5xYKXLnNqAvWCGnsm4xsn5Qfy4d3FGyLiSc7j7WWIhmtLegwVukiK16B7kGdrYi88zqOxONqC0XGWVopyxjV9l+Yg8pOaYIhZSc/srlUCZFPs5b2fEvj0jf1GDxqlAaYH7UQhe56DzD5+XdZRqvmDZwKGSGRuZxB9CLih+gY=
    app: coinaly-api
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
  - provider: heroku
    api_key:
      secure: jpx69wqsXbgk10HxE3f/UsxBug/0CyC0q3hiV55d8sZKWrAAI6VeNHmvXmL2RRdsOamAkUqAlBRjU/SuRK8hCNvrqXX7U8/w4646rkCu5nw2pkBk9YefZOmABMeehmQXssAe42xL9lSbhRH1Ya7+33s+6Xe/D31xE3W8d7aZfiLaoPPbrRyK7IIHTcihBIyT8N+a7aepabIuHLI68RlDBFv1oUvbuWWKC3Qx2MkwBNsEAhSiF7KKyDrCx6fYU/u4srdDKxrI4wDID7ZncVL4tR5mjwT9Frmp99wVQGAo94d3tApcAZ5IfAblZASrEzPDymUTDJe20j4EwaerV4u4AfcVQDD3RW/JpF4Ikog4ndIbRVCGzE144p07iq3Yh2Re2nTA9j7LXeTIrbHJ5Sa8SdoJppNkCppXu/vVNqB5t8+669HVXvbfBylmnCIvOU0r/Wn88k0rR1KM5u/e6IF9ruAQvFFw2ZXcuZBar40eMoQkVFi4KS4yBXwzvNkL8lyLUssV4WiMQIU53iGgqzqBZSilQMJhEO5zzFC+OuBtKQsX5afFgyfr5+gD3ImwAU1DuWWVvy1nQPU2jOZpUHzucIlmsjILow3B1oB8pt7S1M6IELSVu8539OX1S/9m/UxRt4GkdshNX3F3n3GiQ1hdScsehywxeMLkQ71ALzf/LAk=
    app: coinaly-socket
    on:
      repo: jvandenaardweg/coinaly
      branche: master
    skip_cleanup: true
