language: node_js
cache:
  yarn: true
  directories:
  - node_modules
env:
- NODE_ENV=test
deploy:
  - provider: heroku
    api_key:
      secure: ODCeyQS2v1uxLXPzTvOxENzE/8Jr4qQ6IJMSKlnZNMFToJx+Br8rP11GdP3rVR5eEbJOOVlDn/owRGTVTxy91GXrkHhbUW4Qo3s/HdZhh4RaQ+MqFnyr3QWrRW5lZtPHcU6gcwClkHZmrl5QyEbQj4TcHkajzS7O6h9Ab/RraiKLNsNalUtfYkUOZBZboJWxa/dlx8QwaVOB593JsblS6EcaQUFUvI0Qt1IZNQFiig3ryKq0T5aOke8N7cBZNYVGSVONw++KL6ePzOxLctBa/iH0E+LBoBeIL3BcJfCaDJUeXCycIW/66vF/0RFHE3N4jdiSjvQA3IDDxy0qARacMJm9ojhqhC/f2v0e1AgZENFADHN9qFpgd0/A4l0SCfP76ybXTFlcEyezA0bT1prGXZFlJCbj7iyFIohbN+czqNUak/6tljGldTfJESkovNrVQNIZ8LfHpjovmtQnqUtmZfpFnuhCSk6b1iQRR5d8LUeAdWotQS5vx/jdWE20A5jg8/E5tBVSGr4pSxQ0KBwk6hTJB3w3+83NhaoPkphJKI1EJGQmjSP9ShqvkA6OPWFOtnQ17vNx3Izz7WYB9oIMEimoqs3USU0VzoXAKji1OmxyeMECgjcmKL/OcEJFugkxCvVXlVNhrjWNSv6aQbW2q5dcYvmUHI7fayeTFrIJMsc=
    app: coinaly
    on:
      repo: jvandenaardweg/coinaly
      branche: master
  - provider: heroku
    api_key:
      secure: ODCeyQS2v1uxLXPzTvOxENzE/8Jr4qQ6IJMSKlnZNMFToJx+Br8rP11GdP3rVR5eEbJOOVlDn/owRGTVTxy91GXrkHhbUW4Qo3s/HdZhh4RaQ+MqFnyr3QWrRW5lZtPHcU6gcwClkHZmrl5QyEbQj4TcHkajzS7O6h9Ab/RraiKLNsNalUtfYkUOZBZboJWxa/dlx8QwaVOB593JsblS6EcaQUFUvI0Qt1IZNQFiig3ryKq0T5aOke8N7cBZNYVGSVONw++KL6ePzOxLctBa/iH0E+LBoBeIL3BcJfCaDJUeXCycIW/66vF/0RFHE3N4jdiSjvQA3IDDxy0qARacMJm9ojhqhC/f2v0e1AgZENFADHN9qFpgd0/A4l0SCfP76ybXTFlcEyezA0bT1prGXZFlJCbj7iyFIohbN+czqNUak/6tljGldTfJESkovNrVQNIZ8LfHpjovmtQnqUtmZfpFnuhCSk6b1iQRR5d8LUeAdWotQS5vx/jdWE20A5jg8/E5tBVSGr4pSxQ0KBwk6hTJB3w3+83NhaoPkphJKI1EJGQmjSP9ShqvkA6OPWFOtnQ17vNx3Izz7WYB9oIMEimoqs3USU0VzoXAKji1OmxyeMECgjcmKL/OcEJFugkxCvVXlVNhrjWNSv6aQbW2q5dcYvmUHI7fayeTFrIJMsc=
    app: coinaly-api
    on:
      repo: jvandenaardweg/coinaly
      branche: master
  - provider: heroku
    api_key:
      secure: ODCeyQS2v1uxLXPzTvOxENzE/8Jr4qQ6IJMSKlnZNMFToJx+Br8rP11GdP3rVR5eEbJOOVlDn/owRGTVTxy91GXrkHhbUW4Qo3s/HdZhh4RaQ+MqFnyr3QWrRW5lZtPHcU6gcwClkHZmrl5QyEbQj4TcHkajzS7O6h9Ab/RraiKLNsNalUtfYkUOZBZboJWxa/dlx8QwaVOB593JsblS6EcaQUFUvI0Qt1IZNQFiig3ryKq0T5aOke8N7cBZNYVGSVONw++KL6ePzOxLctBa/iH0E+LBoBeIL3BcJfCaDJUeXCycIW/66vF/0RFHE3N4jdiSjvQA3IDDxy0qARacMJm9ojhqhC/f2v0e1AgZENFADHN9qFpgd0/A4l0SCfP76ybXTFlcEyezA0bT1prGXZFlJCbj7iyFIohbN+czqNUak/6tljGldTfJESkovNrVQNIZ8LfHpjovmtQnqUtmZfpFnuhCSk6b1iQRR5d8LUeAdWotQS5vx/jdWE20A5jg8/E5tBVSGr4pSxQ0KBwk6hTJB3w3+83NhaoPkphJKI1EJGQmjSP9ShqvkA6OPWFOtnQ17vNx3Izz7WYB9oIMEimoqs3USU0VzoXAKji1OmxyeMECgjcmKL/OcEJFugkxCvVXlVNhrjWNSv6aQbW2q5dcYvmUHI7fayeTFrIJMsc=
    app: coinaly-socket
    on:
      repo: jvandenaardweg/coinaly
      branche: master
